### ISSUE TITLE
The plugins root package should be adopted to the new namespace

### ISSUE THREAD

**Issue by holgerstolzenberg** [gradle-community/jaxb2#4]

**Comment by deepy** [comment]
With the fix available upstreams I'll be archiving this project

**Comment by deepy** [comment]
I'm re-opening this and intend to do a bunch of Gradle 5 changes, I'll be handling this issue afterwards to make it easy to extract the changes into pull requests.

**Comment by deepy** [comment]
This is done in `3.0.0`
